### ISSUE TITLE
mars-small128.pb

### ISSUE THREAD

**Issue by Andrawzyf** [haandol/mxnet-deepsort-yolo3#2]
hello，i can not find mars-small128.pb in the dir，can you provide？THANKS!

**Comment by haandol** [comment]
Hi, @Andrawzyf . Here is the link, https://github.com/Qidian213/deep_sort_yolov3/blob/master/model_data/mars-small128.pb.

BTW, this was a bug!! this example  does not use mars-small128.pb.

Thank you for report.
